language: python
sudo: false

python:
  - "2.7"
  - "3.5"

install:
  - travis_retry pip install .
  - pip install -r test_requirements.txt

script:
  - make test

notifications:
  email: false
  hipchat:
    on_success: never
    on_failure: change
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
