name: CI

on:
  push:
  pull_request:

jobs:
  run-ci:
    name: Run

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, '3.10', 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies and package
        run: |
          make cideps
          pip install .

      - name: Run tests
        run: make test
